# Generated by Django 5.0.2 on 2025-05-21 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
