# Generated by Django 5.0.2 on 2025-05-21 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cost', models.CharField(max_length=10)),
                ('M', models.CharField(max_length=10)),
                ('T', models.CharField(max_length=10)),
                ('SV', models.CharField(max_length=10)),
                ('W', models.CharField(max_length=10)),
                ('LD', models.CharField(max_length=10)),
                ('OC', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.CharField(max_length=50)),
                ('A', models.CharField(max_length=10)),
                ('WS', models.CharField(max_length=10)),
                ('S', models.CharField(max_length=10)),
                ('AP', models.CharField(max_length=10)),
                ('D', models.CharField(max_length=10)),
                ('keywords', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weapons', to='unitCards.character')),
            ],
        ),
    ]
